# Default values for notifier.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: nareshagrawal/notifier:latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

namespace:
  name: api

progressDeadlineSeconds: 1000
minReadySeconds: 30

deployment:
  type: RollingUpdate
  maxSurge: 1
  maxUnavailable: 0

configmap:
  name: notifier-config
  RDS_CONNECTION_STRING:
  RDS_DB_NAME: 

secret:
  dockercred:
    name: notifier-dockercred
    type: kubernetes.io/dockerconfigjson
    dockerconfigjson:
  rdscred:
    name: notifier-rdscred
    type: Opaque
    username:
    password: